from __future__ import annotations

import json
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import Request, urlopen

from .model import ACTIONS, Rule
from .parser import RuleParseError, parse_remote, parse_text


ACTION_PRIORITY = {"DIRECT": 10, "PROXY": 20, "REJECT": 30}


@dataclass(slots=True)
class Conflict:
    kind: str
    value: str
    kept_action: str
    kept_source: str
    discarded_action: str
    discarded_source: str


class Compiler:
    def __init__(self, root: Path):
        self.root = root
        self.conflicts: list[Conflict] = []

    def build(self, fetch: bool = True) -> dict:
        candidates: list[Rule] = []
        source_counts: Counter[str] = Counter()

        if fetch:
            for rule in self._remote_rules():
                candidates.append(rule)
                source_counts[rule.source] += 1

        for folder, base_priority in (("local", 100), ("private", 200)):
            for action in ACTIONS:
                path = self.root / "rules" / folder / f"{action.lower()}.txt"
                if not path.exists():
                    continue
                source = str(path.relative_to(self.root))
                rules = parse_text(
                    path.read_text(encoding="utf-8"),
                    action,
                    source,
                    base_priority + ACTION_PRIORITY[action],
                )
                candidates.extend(rules)
                source_counts[source] += len(rules)

        resolved = self._resolve(candidates)
        self._write_modules(resolved)
        counts = Counter(rule.action for rule in resolved.values())
        report = {
            "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
            "counts": {action: counts[action] for action in ACTIONS},
            "source_counts": dict(sorted(source_counts.items())),
            "conflict_count": len(self.conflicts),
            "conflicts": [asdict(item) for item in self.conflicts[:100]],
        }
        (self.root / "build-report.json").write_text(
            json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        return report

    def _remote_rules(self):
        config_path = self.root / "config" / "sources.json"
        config = json.loads(config_path.read_text(encoding="utf-8"))
        for source in config.get("sources", []):
            if not source.get("enabled", True):
                continue
            name = source["name"]
            request = Request(source["url"], headers={"User-Agent": "custom-proxy-rules/0.1"})
            with urlopen(request, timeout=60) as response:
                text = response.read().decode("utf-8", "replace")
            action = source["action"].upper()
            yield from parse_remote(
                text,
                source["format"],
                action,
                name,
                ACTION_PRIORITY[action],
            )

    def _resolve(self, candidates: list[Rule]) -> dict[tuple[str, str], Rule]:
        selected: dict[tuple[str, str], Rule] = {}
        for rule in candidates:
            existing = selected.get(rule.key)
            if existing is None:
                selected[rule.key] = rule
                continue
            if existing.action != rule.action:
                winner, loser = (rule, existing) if rule.priority > existing.priority else (existing, rule)
                selected[rule.key] = winner
                self.conflicts.append(
                    Conflict(rule.kind, rule.value, winner.action, winner.source, loser.action, loser.source)
                )
        return selected

    def _write_modules(self, rules: dict[tuple[str, str], Rule]) -> None:
        output = self.root / "dist" / "shadowrocket"
        output.mkdir(parents=True, exist_ok=True)
        for action in ACTIONS:
            selected = sorted(
                (rule for rule in rules.values() if rule.action == action),
                key=lambda item: (item.kind, item.value),
            )
            content = [
                "#!name=Custom Proxy Rules - " + action,
                "#!desc=Generated by custom-proxy-rules. Do not edit this file directly.",
                "",
                "[Rule]",
                *(rule.render() for rule in selected),
                "",
            ]
            (output / f"{action.lower()}.module").write_text("\n".join(content), encoding="utf-8")

