import { readFile, mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ACTIONS, ACTION_PRIORITY, parseRemote, parseText, resolveRules } from "./rules.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
if (process.argv.includes("--lists-only")) {
  await buildListsFromModules();
  process.exit(0);
}
const fetchRemote = !process.argv.includes("--no-fetch");
const candidates = [];
const sourceCounts = {};

if (fetchRemote) {
  const config = JSON.parse(await readFile(resolve(root, "config/sources.json"), "utf8"));
  for (const source of config.sources.filter((item) => item.enabled !== false)) {
    const text = await fetchText(source);
    const rules = parseRemote(text, source.format, source.action, source.name, ACTION_PRIORITY[source.action]);
    candidates.push(...rules);
    sourceCounts[source.name] = rules.length;
  }
}

for (const [folder, basePriority] of [["local", 100], ["private", 200]]) {
  for (const action of ACTIONS) {
    const path = resolve(root, "rules", folder, `${action.toLowerCase()}.txt`);
    if (!existsSync(path)) continue;
    const source = `rules/${folder}/${action.toLowerCase()}.txt`;
    const rules = parseText(await readFile(path, "utf8"), action, source, basePriority + ACTION_PRIORITY[action]);
    candidates.push(...rules);
    sourceCounts[source] = rules.length;
  }
}

const { rules, conflicts } = resolveRules(candidates);
const output = resolve(root, "dist/shadowrocket");
await mkdir(output, { recursive: true });
const counts = Object.fromEntries(ACTIONS.map((action) => [action, rules.filter((rule) => rule.action === action).length]));

for (const action of ACTIONS) {
  const selected = rules.filter((rule) => rule.action === action).sort(sortRules);
  const module = [`#!name=Custom Proxy Rules - ${action}`, "#!desc=Generated by custom-proxy-rules. Do not edit this file directly.", "", "[Rule]", ...selected.map((rule) => rule.render()), ""].join("\n");
  const list = ["# Generated by custom-proxy-rules", ...selected.map((rule) => rule.renderList()), ""].join("\n");
  await writeFile(resolve(output, `${action.toLowerCase()}.module`), module);
  await writeFile(resolve(output, `${action.toLowerCase()}.list`), list);
}

const combined = [...rules].sort((a, b) => b.priority - a.priority || sortRules(a, b));
await writeFile(resolve(output, "all.module"), ["#!name=Custom Proxy Rules", "#!desc=Combined DIRECT, PROXY and REJECT rules generated by custom-proxy-rules.", "", "[Rule]", ...combined.map((rule) => rule.render()), ""].join("\n"));

const report = {
  generated_at: new Date().toISOString().replace(/\.\d{3}Z$/, "Z"), counts,
  source_counts: Object.fromEntries(Object.entries(sourceCounts).sort()),
  conflict_count: conflicts.length, conflicts: conflicts.slice(0, 100),
};
await writeFile(resolve(root, "build-report.json"), `${JSON.stringify(report, null, 2)}\n`);
console.log(JSON.stringify(counts));
console.log(`conflicts: ${conflicts.length}`);

function sortRules(a, b) { return a.kind.localeCompare(b.kind) || a.value.localeCompare(b.value); }

async function fetchText(source) {
  let lastError;
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
      const response = await fetch(source.url, {
        headers: { "user-agent": "custom-proxy-rules/0.2" },
        signal: AbortSignal.timeout(120_000),
      });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      return await response.text();
    } catch (error) {
      lastError = error;
      if (attempt < 3) console.warn(`${source.name}: attempt ${attempt} failed, retrying…`);
    }
  }
  throw new Error(`${source.name}: download failed after 3 attempts: ${lastError.message}`);
}

async function buildListsFromModules() {
  const output = resolve(root, "dist/shadowrocket");
  for (const action of ACTIONS) {
    const module = await readFile(resolve(output, `${action.toLowerCase()}.module`), "utf8");
    const lines = module.split(/\r?\n/).filter((line) => line && !line.startsWith("#") && line !== "[Rule]");
    const list = lines.map((line) => {
      const parts = line.split(",");
      return [parts[0], parts[1], ...parts.slice(3)].join(",");
    });
    await writeFile(resolve(output, `${action.toLowerCase()}.list`), ["# Generated by custom-proxy-rules", ...list, ""].join("\n"));
  }
  console.log("rule lists rebuilt from existing modules");
}
